### ISSUE TITLE
Decide on author order and contribution/task breakdown (for JOSE paper)

### ISSUE THREAD

**Issue by lwjohnst86** [UofTCoders/paper-rcourse#2]

**Comment by lwjohnst86** [comment]
To make our roles/contributions more clear, we should decide on how we will breakdown the different tasks, who wants to do what, who doesn't want to contribute (busy, etc), and so on. This will also help decide on author order.

**Comment by mbonsma** [comment]
I'm happy to do writing but will probably be sporadically busy (like all of us I guess). It might also help to make a roadmap of tasks since not everything can happen concurrently?

**Comment by mbonsma** [comment]
Made a roadmap - #7. Feel free to edit! We can add people's names to specific points or subdivide tasks as we go.

**Comment by aays** [comment]
Current iteration looks good to me!

**Comment by SaraMati** [comment]
👍

**Comment by James-S-Santangelo** [comment]
Looks good to me.

**Comment by lwjohnst86** [comment]
Looks good to me too

**Comment by mbonsma** [comment]
Me too!

**Comment by lwjohnst86** [comment]
Since there are no objections, I'll keep the order as is right now.

**Comment by joelostblom** [comment]
Is this the current author order?

```
# Author order? Right now it is alphabetical
authors:
- name: Luke W. Johnston
  orcid: 0000-0003-4169-2616
  affiliation: "2,3"
- name: Madeleine Bonsma-Fisher
  orcid: 0000-0002-5813-4664
  affiliation: 1
- name: Lindsay Coome
  orcid:
  affiliation: 5
- name: Joel Ostblom
  orcid: 0000-0003-0051-3239
  affiliation: 4
- name: Elliott Sales de Andrade
  orcid: 0000-0001-7310-8942
  affiliation: 1
- name: Lina Tran
  orcid: 0000-0003-3504-4524
  affiliation: 8
- name: Ahmed R. Hasan
  orcid: 0000-0003-0002-8399
  affiliation: 6
- name: James S. Santangelo
  orcid: 0000-0002-5921-2548
  affiliation: 7
- name: Sara Mahallati
  orcid: 0000-0002-6765-0898
  affiliation: 4
```

Will it be made alphabetical (by lastname?), and the author contributions are just listed in the contributions section? Or are we meaning for this to also be indicative of the contributions to either the course or the paper writing? There are no instructions from JOSE on this so it seems like we can choose. I guess last author = supervisor is at least not happening.
